day13/django_crud/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # Create
    path('signup/', views.signup, name="signup"), # GET, POST

    # Read
    path('myaccount/', views.myaccount, name="myaccount"), # GET

    # Update
    path('update_account/', views.update_account, name="update_account"), # GET, POST

    # Delete
    path('signout/', views.signout, name="signout"), # GET, POST

    # Login
    path('login/', views.user_login, name="login"), # GET, POST

    # Logout
    path('logout/', views.user_logout, name="logout"), # POST
]

day13/django_crud/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    # index
    path('', views.index, name="index"),

    # Create
    path('create/', views.create, name="create"),

    # Read
    path('<int:article_id>/', views.read, name="read"),

    # Update
    path('<int:article_id>/update/', views.update, name="update"),

    # Delete
    path('<int:article_id>/delete/', views.delete, name="delete"),

    # comment

    # Create
    path('<int:article_id>/comments/create/', views.comment_create, name="comment_create"),

    # Update
    path('<int:article_id>/comments/<int:comment_id>/update/', views.comment_update, name="comment_update"),

    # Delete
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name="comment_delete"),

]

day13/django_crud/django_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("articles.urls")),
    path('accounts/', include("accounts.urls")),
]

day13/django_crud/accounts/models.py
from django.db import models

# Create your models here.

day13/django_crud/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, related_name="articles", on_delete=models.CASCADE, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"id: {self.pk} / title: {self.title}"


class Comment(models.Model):
    article = models.ForeignKey(Article, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(User, related_name="aa_comments", on_delete=models.CASCADE, null=True)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"content: {self.content}"

day13/django_crud/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, get_user

# Create your views here.
def signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()

        login(request, user)
        return redirect("articles:index")
    else:
        return render(request, "accounts/signup.html")

def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        return redirect("articles:index")
    else:
        return render(request, "accounts/login.html")

def user_logout(request):
    logout(request)
    return redirect("articles:index")

def signout(request):
    if request.method == "POST":
        user = get_user(request)
        user.delete()
    return redirect("articles:index")

def myaccount(request):
    return render(request, "accounts/myaccount.html")

def update_account(request):
    if request.method == "POST":
        email = request.POST.get("email")
        user = get_user(request)
        user.email = email
        user.save()
        return redirect("accounts:myaccount")
    else:
        return render(request, "accounts/update_account.html")

day13/django_crud/articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, get_user

# Create your views here.
def index(request):
    context = {}
    articles = Article.objects.all()
    context["articles"] = articles
    return render(request, "articles/index.html", context)

def create(request):
    if request.method == "POST":
        user = get_user(request)
        print(user)
        if not user.is_authenticated:
            return redirect("articles:index")
        article = Article()
        article.title = request.POST.get("title")
        article.content = request.POST.get("content")
        article.author = user
        article.save()

        return redirect("articles:index")
    else:
        return render(request, "articles/create.html")

def read(request, article_id):
    context = {}
    article = Article.objects.get(pk=article_id)
    context["article"] = article
    return render(request, "articles/read.html", context=context)

def update(request, article_id):
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")

        article = Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()

        return redirect("articles:index")
    else:
        context = {}
        article = Article.objects.get(pk=article_id)
        context["article"] = article
        return render(request, "articles/update.html", context=context)

def delete(request, article_id):
    if request.method == "GET":
        article = Article.objects.get(pk=article_id)

        current_user = get_user(request)
        if article.author != current_user:
            return redirect("articles:index")
        article.delete()
    
    return redirect("articles:index")

def comment_create(request, article_id):
    if request.method == "POST":
        content = request.POST.get("content")
        comment = Comment()
        comment.article = Article.objects.get(pk=article_id)
        comment.content = content
        comment.save()
    return redirect("articles:read", article_id)

def comment_update(request, article_id, comment_id):
    if request.method == "POST":
        content = request.POST.get("content")
        comment = Comment.objects.get(pk=comment_id)
        comment.content = content
        comment.save()
    return redirect("articles:read", article_id)

def comment_delete(request, article_id, comment_id):
    if request.method == "POST":
        comment = Comment.objects.get(pk=comment_id)
        comment.delete()
    return redirect("articles:read", article_id)

day13/django_crud/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h2>로그인</h2>
<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username"><br>
    <input type="password" name="password"><br>
    <input type="submit" vlaue="로그인">
</form>
{% endblock %}

day13/django_crud/accounts/templates/accounts/myaccount.html
{% extends 'base.html' %}
{% block content %}
<h2>회원 정보</h2>
<p>
    username: {{user.username}} <br>
    email: {{user.email}} <br>
    <form action="{% url 'accounts:signout' %}" method="POST">
        {% csrf_token %}
        <a href="{% url 'accounts:update_account' %}" class="btn btn-outline-primary">회원정보 수정</a>
        <input type="submit" value="회원탈퇴" class="btn btn-outline-primary">
    </form>
</p>
{% endblock %}

day13/django_crud/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h2>회원가입</h2>
<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    <label for="username">username: </label>
    <input type="text" name="username" id="username"> <br><br>
    <label for="email">email: </label>
    <input type="email" name="email" id="email"> <br><br>
    <label for="password">password: </label>
    <input type="password" name="password" id="password">
    <input type="submit" value="회원가입">
</form>
{% endblock %}

day13/django_crud/accounts/templates/accounts/update_account.html
{% extends 'base.html' %}

{% block content %}
<h2>이메일 업데이트</h2>
<form action="{% url 'accounts:update_account' %}" method="POST">
    {% csrf_token %}
    <input type="email" value="{{user.email}}" name="email">
    <input type="submit" value="업데이트">
</form>
{% endblock %}


<!-- fastapi -->
<!-- gabia: domain -->
<!-- aws lightsail -->

day13/django_crud/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<h2>게시물 생성</h2>

<div class="mt-2">
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">title</span>
            </div>
            <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" name="title">
        </div>
        <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">content</span>
            </div>
            <textarea class="form-control" aria-label="With textarea" name="content"></textarea>
        </div>
        <br>
        <input type="submit" value="생성" class="btn btn-outline-primary">
        <a href="{% url 'articles:index' %}" class="btn btn-outline-primary">목록으로 돌아가기</a>
    </form>
</div>

{% endblock %}

day13/django_crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h2>articles</h2>
<br><br>
<div style="text-align: right;">
  <a href="{% url 'articles:create' %}" class="btn btn-outline-primary">게시물 생성</a><br><br>
</div>

<ul class="list-group">
  {% for article in articles %}
  
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="{% url 'articles:read' article.pk %}" class="btn">{{article.title}} / author: {{article.author.username}}</a>  
    <span class="badge"><a href="{% url 'articles:delete' article.pk %}" class="mx-2 btn btn-outline-primary">게시물 삭제</a></span>
  </li>
    {% empty %}
    게시물이 없습니다!!
    {% endfor %}
</ul>
{% endblock %}

day13/django_crud/articles/templates/articles/read.html
{% extends 'base.html' %}

{% block content %}
<h2>
    title: {{article.title}}
</h2>
<p>
    content: {{article.content}}
</p>
<p>
    created_at : {{article.created_at}}
    updated_at : {{article.updated_at}}
</p>

<!-- comment 생성 -->
<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="text" name="content">
    <input type="submit" class="btn btn-outline-primary" value="댓글 달기">
</form>

{% for comment in article.comments.all %}
<p id="comment-{{comment.id}}-p">
    <!-- comment 불러오기 -->
    comment {{comment.pk}}:<span id="comment-{{comment.id}}"> {{comment.content}}</span>
    <!-- comment update -->
    <span class="btn btn-outline-primary" id="comment-{{comment.id}}-btn" onclick="javascript:update_comment('{{article.id}}', '{{comment.id}}')">수정</span>
    <!-- comment 삭제 -->
    <span class="btn btn-outline-primary" onclick="javascript:post_comment_delete('{{article.id}}', '{{comment.id}}')">삭제</span>
    
</p>
{% empty %}
    댓글이 없습니다.
{% endfor %}

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = 'X-CSRFToken';

    function post_comment_update(article_id, comment_id, content)
    {
        var data = `content=${content}`;
        axios.post(`/${article_id}/comments/${comment_id}/update/`, data)
        .then(function(response) {
          console.log(response);
          window.location.reload()
        })
        .catch(function(error) {
          console.log(error);
        });
    }

    function post_comment_delete(article_id, comment_id)
    {
        axios.post(`/${article_id}/comments/${comment_id}/delete/`)
        .then(function(response) {
          console.log(response);
          window.location.reload()
        })
        .catch(function(error) {
          console.log(error);
        });
    }


    function update_comment(article_id, comment_id)
    {
        var comment = document.getElementById(`comment-${comment_id}-p`);
        var div = document.createElement('div');

        var content = document.createElement('input');
        content.value = document.getElementById(`comment-${comment_id}`).innerText

        var btnUpdate = document.createElement('input');
        btnUpdate.type = "button";
        btnUpdate.value= "업데이트";
        btnUpdate.className += "btn btn-outline-primary";
        btnUpdate.addEventListener("click", function(){post_comment_update(article_id, comment_id, content.value)}, false);

        div.appendChild(content);
        div.appendChild(btnUpdate);

        comment.appendChild(div)
    }
</script>
{% endblock %}

day13/django_crud/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="text" name="title" value="{{article.title}}">
    <input type="text" name="content" value="{{article.content}}">
    <input type="submit" value="업데이트">
</form>
{% endblock %}

day13/django_crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <header class="mb-2">
        {% include 'navbar.html' %}
    </header>
    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer>

    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

day13/django_crud/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Article</span></a>
            </li>
        </ul>
    </div>

    <div class="d-flex">
        {% if user.is_authenticated %}
            <span>안녕하세요 <a href="{% url 'accounts:myaccount' %}">{{user.username}}</a>님!!</span>
            <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="로그아웃" class="btn btn-outline-primary">
            </form>
            <!-- <a href="{% url 'accounts:logout' %}" class="btn btn-outline-primary">로그아웃</a> -->
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary">로그인</a>
            <a href="{% url 'accounts:signup' %}" class="btn btn-outline-primary">회원가입</a>
        {% endif %}
    </div>

</nav>